---
- name: Launch application
  community.docker.docker_container:
      name: "{{ app_container_name }}"
      image: "{{ app_image }}"
      state: started
      restart_policy: unless-stopped
      networks:
          - name: app-network
      env:
          SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/{{ db_name }}"
          SPRING_DATASOURCE_USERNAME: "{{ db_user }}"
          SPRING_DATASOURCE_PASSWORD: "{{ db_password }}"
  no_log: true
