---
- name: Launch database
  community.docker.docker_container:
    name: "{{ db_container_name }}"
    image: "{{ db_image }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ db_name }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
    volumes:
      - postgres_data_tp2:/var/lib/postgresql/data