---
db_container_name: database
db_image: eugenelallain/tp2-docker-devops-db:latest
db_name: "{{ lookup('ansible.builtin.env', 'DB_NAME') }}"
db_user: "{{ lookup('ansible.builtin.env', 'DB_USER') }}"
db_password: "{{ lookup('ansible.builtin.env', 'DB_PASSWORD') }}"
